### ISSUE TITLE
Exception on TorSharpToolFetcher

### ISSUE THREAD

**Issue by Spegeli** [joelverhagen/TorSharp#23]
Currently
`await new TorSharpToolFetcher(torSettings, new HttpClient()).FetchAsync();`
throws an exception for me:
> The element named 'html' and the namespace '' is not a valid feed format.

Is the Download URL maybe no longer Update2Date?

**Comment by joelverhagen** [comment]
Thanks for the heads up. Let me check it out.

**Comment by joelverhagen** [comment]
Seems to be due to a SourceForge outage. Privoxy can't be downloaded right now.

http://sourceforge.net/projects/ijbswa/rss?path=/Win32
... redirects to...
https://sourceforge.net/error-404.html?project=ijbswa

**Comment by joelverhagen** [comment]
I've fixed the issue and pushed version 1.8.1 to NuGet.org:
https://www.nuget.org/packages/Knapcode.TorSharp/1.8.1

**Comment by Spegeli** [comment]
@joelverhagen 

Today we got another problem:
https://sourceforge.net/projects/ijbswa/rss?path=/Win32 **is up again**
**but** https://www.privoxy.org/feeds/privoxy-releases.xml **is down**

can you integrate both and use one as backup?

**Comment by joelverhagen** [comment]
You're kidding me!!! Yup, sounds like we need a fallback strategy 😄.

**Comment by joelverhagen** [comment]
Alright, let's try this again. I've release a 1.8.2:
https://www.nuget.org/packages/Knapcode.TorSharp/1.8.2

It tries these three:
https://www.privoxy.org/feeds/privoxy-releases.xml
https://sourceforge.net/projects/ijbswa/rss?path=/Win32
https://www.silvester.org.uk/privoxy/Windows/ (official mirror)

Also, I had to turn on TLS 1.1 since SourceForge seems to be requiring that now.
