### ISSUE TITLE
Can't fetch files nor configure manually

### ISSUE THREAD

**Issue by ajhalls** [joelverhagen/TorSharp#40]
Trying to use the sample code results in the following error:
`Knapcode.TorSharp.TorSharpException: 'Failed to extract tool 'Tor'. Verify that the .zip at path 'C:\Users\Alan\AppData\Local\Temp\TorZipped\tor-win32-0.4.1.5.zip' is valid.'`

Looking at the file shows it is only 124k in size, and the one for Privoxy is 0k.

I then tried manually downloading and setting it up, it gets past the problem with Tor, but can't detect that Privoxy is there and an error is thrown on the line:
  `                  await proxy.ConfigureAndStartAsync();
`

**Comment by joelverhagen** [comment]
I think what's going on here is a bug that was fixed by @MahmutYaman: https://github.com/joelverhagen/TorSharp/pull/37.

I merged the changes and just now released a fix in 2.0.1:
https://www.nuget.org/packages/Knapcode.TorSharp/2.0.1

Could you update to latest and let me know if this fixed the problem for you?

If Privoxy is 0k, then I think the download failed perhaps because the download site was being flaky. I think I can improve the download logic to only accept one of the download sites if it returns a non-empty, valid .zip file.

**Comment by joelverhagen** [comment]
Closing. If updating to the latest version does not help you, let me know.
