### ISSUE TITLE
/tmp/TorExtracted/privoxy-linux64-3.0.28/usr/sbin/privoxy: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by roikra** [joelverhagen/TorSharp#42]
Getting the following error when running the code:
**/tmp/TorExtracted/privoxy-linux64-3.0.28/usr/sbin/privoxy: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory**

**Comment by joelverhagen** [comment]
Could you tell me what distribution you are on? I think the easiest workaround is to find what package in your distro's package manager brings `libpcre.so.3` and install that.

**Comment by roikra** [comment]
I am using Centos7 (on which I was not able to fix the libpcre.so.3 issue).
On the official images for the .NET Core runtime  (Debian 9) the code works with no errors.

**Comment by joelverhagen** [comment]
I can repro the problem on a CentOS 7 VM. Root cause is that the Privoxy binary that TorSharp downloads is compiled for a Debian environment (where libpcre is currently versioned at `libpcre.so.3`). I think the best option here is enhance TorSharp to fall back to a system-provided Privoxy (one available in the environment via something like `yum install privoxy`). This work is not done yet so I'll leave this issue open to track that.

**Comment by joelverhagen** [comment]
I have enabled usage of an installed version of Privoxy. I tried this out on CentOS 7 and it works fine. This is able with version 2.1.0 of TorSharp. I put more detailed instructions in the README: [CentOS 7](https://github.com/joelverhagen/TorSharp#centos-7).
