### ISSUE TITLE
Problem during the upgrade process

### ISSUE THREAD

**Issue by odi1n** [joelverhagen/TorSharp#43]
In General, observed such a thing: when constantly or every 1-2m you update process, through some time(always it different), simply plainly work does freeze on renewal, i.e. suppose program has updated proxy and work has stalled, I learned button, by clicking on it should be updated proxy somewhere in during 10 minutes after stop, it perhaps again starts work but most often account for launch process with the outset. It seems to me there is no certain exception or check whether the method works or not.

**Comment by joelverhagen** [comment]
I'm sorry, I don't understand what you mean. Could you describe:

1. What steps you are taking to encounter the problem
1. What you except to happen
1. What is actually happening

**Comment by odi1n** [comment]
OK, sorry for my poor English, use a translator. I have a project parsing the site, when the site can not get the information I use the GetNewIdentityAsync method and update the proxy and the site loads again, but the site has such a thing that not all proxies are suitable, I have to use this method(5-10-50 times all this in a loop and on async/await) to update the proxy. At one such point, when I use this method, it just doesn't work (it happens somewhere at all after 20-100 times of updating) and all the work stops. I found a solution that helped me partially eliminate this point, I use first ConfigureAndStartAsync, then GetNewIdentityAsync, after which it became much longer to work (1000-5000), also tried to use the StartProxy method, then it is enough for (5-10K reboots). Figures approximate, can occur both to these limits, and later. Here is the part of the code where the technique is used, the work stops on ConfigureAndStartAsync or GetNewIdentityAsync, when, how, after working, the way in which this is used all stops, after which the record to re-run this method

```sharp
    Task.Run(() =>
    {
        tor.StartProxy();
        tor.ProxyRestart.ConfigureAndStartAsync();
        tor.ProxyRestart.GetNewIdentityAsync();
    });
```

**Comment by joelverhagen** [comment]
I'm not exactly sure of the root cause here but it sounds like Tor is rate-limiting the `NEWNYM` signal (which is used by `GetNewIdentityAsync` to try to get a new identity). Attempting to circumvent such rate limiting goes against the design of the Tor client and I wouldn't feel comfortable doing so.

For more details, see the [control-spec.txt `NEWNYM` signal documentaiton](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt?id=5bd5f82e3d4319f591157c1a3d717c25e44a33a5#n444).

My best recommendation is to use an established circuit for more time and reduce the number of times you are restarting Tor or trying to get a new identity.
