### ISSUE TITLE
is possible to monitor traffic data  (upload, download)?

### ISSUE THREAD

**Issue by username77** [joelverhagen/TorSharp#44]
I see some stats every 6h about bandwidth, status (Heartbeat: Tor's uptime is 6:00 hours, with 3 circuits open.  I've sent 4.27 MB and received 9.57 MB.) but i'm not able to find who is located the code.

Is possible to call it when i need it?

**Comment by joelverhagen** [comment]
Yes, this is quite possible. This can be easily done using the Tor control protocol. The Tor executable is actually listening on two ports: a SOCKS port (which Privoxy connects to in TorSharp) and a control port. The control port is used today by TorSharp when you call `TorSharpProxy.GetNewIdentityAsync`.

You can easily play around with the control protocol using Putty and a raw TCP connection against `localhost:{control port}`.

![image](https://user-images.githubusercontent.com/94054/68608513-fb26fb80-0467-11ea-9b7a-94a6780d4bcd.png)

![image](https://user-images.githubusercontent.com/94054/68608553-0ed26200-0468-11ea-95ef-6e7f71add228.png)

I think it would be great to have these two ["GETINFO" calls available](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt?id=5bd5f82e3d4319f591157c1a3d717c25e44a33a5#n726) as methods on `TorControlClient`. The `SendCommandAsync` method would need some enhancements because it only expects a single line `250 OK` today, but it should be pretty easy.

Would you be interested in contributing this change?

**Comment by username77** [comment]
> Yes, this is quite possible. This can be easily done using the Tor control protocol. The Tor executable is actually listening on two ports: a SOCKS port (which Privoxy connects to in TorSharp) and a control port. The control port is used today by TorSharp when you call `TorSharpProxy.GetNewIdentityAsync`.
> 
> You can easily play around with the control protocol using Putty and a raw TCP connection against `localhost:{control port}`.
> 
> ![image](https://user-images.githubusercontent.com/94054/68608513-fb26fb80-0467-11ea-9b7a-94a6780d4bcd.png)
> 
> ![image](https://user-images.githubusercontent.com/94054/68608553-0ed26200-0468-11ea-95ef-6e7f71add228.png)
> 
> I think it would be great to have these two ["GETINFO" calls available](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt?id=5bd5f82e3d4319f591157c1a3d717c25e44a33a5#n726) as methods on `TorControlClient`. The `SendCommandAsync` method would need some enhancements because it only expects a single line `250 OK` today, but it should be pretty easy.
> 
> Would you be interested in contributing this change?

added here the call:
https://github.com/joelverhagen/TorSharp/pull/45#issue-339652028

**Comment by joelverhagen** [comment]
Added support for this to https://www.nuget.org/packages/Knapcode.TorSharp/2.2.0. Thanks for the PR @username77! 

Sample here:
https://github.com/joelverhagen/TorSharp/blob/37b2d5db30b4b380dfc6d4f91c70683b6791c433/samples/TorSharp.Sandbox/Program.cs#L81-L87
