### ISSUE TITLE
403 question

### ISSUE THREAD

**Issue by seanstardev** [joelverhagen/TorSharp#67]
I notice that some sites seem to block Tor and always return a 403. Yet Tor Browser is able to access these pages just fine.

Is there a reason for this? Really appreciate any insight.

**Comment by joelverhagen** [comment]
I think to determine the root cause, a detailed analysis of the network traffic and Tor Browser behavior would be required. This analysis is not something I am in the business of doing. I'm just letting you know that Tor Browser is a full web browsing stack whereas traffic done through TorSharp is likely very simple in nature (when compared to a web browser).

Regarding this 403 you are encountering, I recommend taking this error code as a signal that this site is not interested in scripted traffic. Consider contacting the owner of the site you are making HTTP requests against to understand the root cause.

**Comment by seanstardev** [comment]
Thank you so much for the response :)

It is an entirely academic question, no worries. I just stumbled across the phenomenon recently and can't for the life of me figure out why the browser avoids getting 403s, while directly using tor.exe does. I thought it might have something to do with custom browser torrc file settings, but alas no.

Thanks again for your time @joelverhagen
